name: chumzy
description: "Your study buddy, sharp and ready!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.11
  gap: ^3.0.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/chumzy_character/chumzy_app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/chumzy_character/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/json/
